name: CI

on:
    pull_request:
        branches: ["*"]
    push:
        branches: ["main"]

jobs:
    docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: "21"

            - name: Build & Push with Jib
              env:
                  IMAGE_VERSION: ${{ github.sha }}
                  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
              run: ./gradlew jib